### ISSUE TITLE
Sometimes it doesn't hide, only if i unmaximize and maximize again

### ISSUE THREAD

**Issue by hrqmonteiro** [luisbocanegra/kwin-panel-auto-hide#8]
https://github.com/luisbocanegra/kwin-panel-auto-hide/assets/17055027/4e9ee0a1-2068-4bbd-b0ed-875814845db7

**Comment by luisbocanegra** [comment]
I can reproduce this one. Will try to take a look when I get the time. 

Note that Plasma 6 will have this feature built-in, haven't tried it on my main system yet but (in the case of the official implementation being enough for me) is very likely that I will upgrade and will have to mark this project as unmaintained.

**Comment by luisbocanegra** [comment]
Hi. Now that Plasma 6 has been released with Dodge Window feature builtin, I have no need to keep developing this anymore (not that I was doing much anyway, no commits for 8 months!).

If anyone else need to have this on plasma 5 feel free to fork and fix it our start a new one.

Thanks for your time trying it out!
