### ISSUE TITLE
How to desable this script

### ISSUE THREAD

**Issue by abhishekcs0** [luisbocanegra/kwin-panel-auto-hide#9]
Hello, I was just trying this script the autohide works, but now I can't go back to normal mode, I disabled script, deleted it, restart system nothing works 

Update: Well I was dumb, there is option when enter edit mode on top panel > more options > Auto Hide > Always Visible.

**Comment by luisbocanegra** [comment]
Yeah, I could've added a cleanup task that restored the previous panel visibility. 

But since this is builtin in Plasma 6, which I am using and this project won't have any further development, I think is better to archive it
